import ProductsDisplayAdmin from './ProductsDisplayAdmin';


export const metadata = {
  title: 'Home Page',
  description: 'Generated by create next app',
}


export const revalidate = 0.3;
// Data will be fetch from locagost:3000/api/product/read at every 01 sec....

export default async function Home() {

  return (
    <>

      <div className="flex flex-col gap-y-10">
        <main className="px-5">
          <div className="flex flex-col gap-y-5 my-10">
            <ProductsDisplayAdmin></ProductsDisplayAdmin>
          </div>

        </main>
      </div>
    </>
  )
}
